kind: Service
apiVersion: v1
metadata:
  name: my-drone-app-service
spec:
  selector:
    app: drone-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drone-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: drone.dronecluster.us-south.containers.appdomain.cloud
    http:
      paths:
      - backend:
          serviceName: my-drone-app-service
          servicePort: 80
        path: /